[package]
name = "pdmn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.2"
clap = { version = "4.1.4", features = ["derive"] }
dirs = "4.0.0"
url = "2.3.1"
